import Head from "next/head";
function contact() {
  return (
    <>
      <div>Contact us</div>{" "}
      <Head>
        <title>Contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

export default contact;
